import os

from setuptools import find_packages

from distutils.core import setup
from distutils.extension import Extension

from Cython.Build import cythonize

import numpy


PARASAIL_INCLUDE = os.environ['PARASAIL_INCLUDE']
PARASAIL_LIB = os.environ['PARASAIL_LIB']


def extension(name, sources):
    return Extension(
        name, sources,
        include_dirs=[PARASAIL_INCLUDE, numpy.get_include()],
        library_dirs=[PARASAIL_LIB],
        extra_link_args=["-Wl,-rpath,{}".format(PARASAIL_LIB)],
        runtime_library_dirs=[PARASAIL_LIB],
        libraries=['parasail'])


extensions = [
    extension('cyparasail._parasail_base', ["cyparasail/_parasail_base.pyx"]),
    extension('cyparasail._parasail_ssw', ["cyparasail/_parasail_ssw.pyx"]),
    extension('cyparasail._autogenerated', ["cyparasail/_autogenerated.pyx"]),
    extension('cyparasail._result', ["cyparasail/_result.pyx"]),
    extension('cyparasail._cigar', ["cyparasail/_cigar.pyx"]),
]

setup(
    name="parasail-cython",
    version="0.0.1",
    packages=find_packages(),
    ext_modules=cythonize(extensions),
)
