import os
import sys

from setuptools import find_packages

from distutils.core import setup
from distutils.extension import Extension

from Cython.Build import cythonize

import numpy


PARASAIL_INCLUDE = os.environ['PARASAIL_INCLUDE']
PARASAIL_LIB = os.environ['PARASAIL_LIB']

if sys.platform == "win32":
    RUNTIME_LIBRARY_DIRS = []
    EXTRA_LINK_ARGS = []
else:
    # assume posix
    RUNTIME_LIBRARY_DIRS = [PARASAIL_LIB]
    EXTRA_LINK_ARGS = ["-Wl,-rpath,{}".format(PARASAIL_LIB)]


def extension(name, sources):
    return Extension(
        name, sources,
        include_dirs=[PARASAIL_INCLUDE, numpy.get_include()],
        library_dirs=[PARASAIL_LIB],
        extra_link_args=EXTRA_LINK_ARGS,
        runtime_library_dirs=RUNTIME_LIBRARY_DIRS,
        libraries=['parasail']
    )


extensions = [
    extension('cyparasail._parasail_base', ["cyparasail/_parasail_base.pyx"]),
    extension('cyparasail._parasail_ssw', ["cyparasail/_parasail_ssw.pyx"]),
    extension('cyparasail._autogenerated', ["cyparasail/_autogenerated.pyx"]),
    extension('cyparasail._result', ["cyparasail/_result.pyx"]),
    extension('cyparasail._cigar', ["cyparasail/_cigar.pyx"]),
]

setup(
    name="parasail-cython",
    version="0.0.1",
    packages=find_packages(),
    ext_modules=cythonize(extensions),
)
