from __future__ import print_function, unicode_literals

import argparse


FUNC_NAMES = [
    'parasail_nw',
    'parasail_nw_table',
    'parasail_nw_rowcol',
    'parasail_nw_trace',
    'parasail_nw_stats',
    'parasail_nw_stats_table',
    'parasail_nw_stats_rowcol',
    'parasail_sg',
    'parasail_sg_table',
    'parasail_sg_rowcol',
    'parasail_sg_trace',
    'parasail_sg_stats',
    'parasail_sg_stats_table',
    'parasail_sg_stats_rowcol',
    'parasail_sw',
    'parasail_sw_table',
    'parasail_sw_rowcol',
    'parasail_sw_trace',
    'parasail_sw_stats',
    'parasail_sw_stats_table',
    'parasail_sw_stats_rowcol',
    'parasail_nw_scan',
    'parasail_nw_table_scan',
    'parasail_nw_rowcol_scan',
    'parasail_nw_trace_scan',
    'parasail_nw_stats_scan',
    'parasail_nw_stats_table_scan',
    'parasail_nw_stats_rowcol_scan',
    'parasail_sg_scan',
    'parasail_sg_table_scan',
    'parasail_sg_rowcol_scan',
    'parasail_sg_trace_scan',
    'parasail_sg_stats_scan',
    'parasail_sg_stats_table_scan',
    'parasail_sg_stats_rowcol_scan',
    'parasail_sw_scan',
    'parasail_sw_table_scan',
    'parasail_sw_rowcol_scan',
    'parasail_sw_trace_scan',
    'parasail_sw_stats_scan',
    'parasail_sw_stats_table_scan',
    'parasail_sw_stats_rowcol_scan',
    'parasail_nw_scan_64',
    'parasail_nw_scan_32',
    'parasail_nw_scan_16',
    'parasail_nw_scan_8',
    'parasail_nw_scan_sat',
    'parasail_nw_striped_64',
    'parasail_nw_striped_32',
    'parasail_nw_striped_16',
    'parasail_nw_striped_8',
    'parasail_nw_striped_sat',
    'parasail_nw_diag_64',
    'parasail_nw_diag_32',
    'parasail_nw_diag_16',
    'parasail_nw_diag_8',
    'parasail_nw_diag_sat',
    'parasail_nw_table_scan_64',
    'parasail_nw_table_scan_32',
    'parasail_nw_table_scan_16',
    'parasail_nw_table_scan_8',
    'parasail_nw_table_scan_sat',
    'parasail_nw_table_striped_64',
    'parasail_nw_table_striped_32',
    'parasail_nw_table_striped_16',
    'parasail_nw_table_striped_8',
    'parasail_nw_table_striped_sat',
    'parasail_nw_table_diag_64',
    'parasail_nw_table_diag_32',
    'parasail_nw_table_diag_16',
    'parasail_nw_table_diag_8',
    'parasail_nw_table_diag_sat',
    'parasail_nw_rowcol_scan_64',
    'parasail_nw_rowcol_scan_32',
    'parasail_nw_rowcol_scan_16',
    'parasail_nw_rowcol_scan_8',
    'parasail_nw_rowcol_scan_sat',
    'parasail_nw_rowcol_striped_64',
    'parasail_nw_rowcol_striped_32',
    'parasail_nw_rowcol_striped_16',
    'parasail_nw_rowcol_striped_8',
    'parasail_nw_rowcol_striped_sat',
    'parasail_nw_rowcol_diag_64',
    'parasail_nw_rowcol_diag_32',
    'parasail_nw_rowcol_diag_16',
    'parasail_nw_rowcol_diag_8',
    'parasail_nw_rowcol_diag_sat',
    'parasail_nw_trace_scan_64',
    'parasail_nw_trace_scan_32',
    'parasail_nw_trace_scan_16',
    'parasail_nw_trace_scan_8',
    'parasail_nw_trace_scan_sat',
    'parasail_nw_trace_striped_64',
    'parasail_nw_trace_striped_32',
    'parasail_nw_trace_striped_16',
    'parasail_nw_trace_striped_8',
    'parasail_nw_trace_striped_sat',
    'parasail_nw_trace_diag_64',
    'parasail_nw_trace_diag_32',
    'parasail_nw_trace_diag_16',
    'parasail_nw_trace_diag_8',
    'parasail_nw_trace_diag_sat',
    'parasail_nw_stats_scan_64',
    'parasail_nw_stats_scan_32',
    'parasail_nw_stats_scan_16',
    'parasail_nw_stats_scan_8',
    'parasail_nw_stats_scan_sat',
    'parasail_nw_stats_striped_64',
    'parasail_nw_stats_striped_32',
    'parasail_nw_stats_striped_16',
    'parasail_nw_stats_striped_8',
    'parasail_nw_stats_striped_sat',
    'parasail_nw_stats_diag_64',
    'parasail_nw_stats_diag_32',
    'parasail_nw_stats_diag_16',
    'parasail_nw_stats_diag_8',
    'parasail_nw_stats_diag_sat',
    'parasail_nw_stats_table_scan_64',
    'parasail_nw_stats_table_scan_32',
    'parasail_nw_stats_table_scan_16',
    'parasail_nw_stats_table_scan_8',
    'parasail_nw_stats_table_scan_sat',
    'parasail_nw_stats_table_striped_64',
    'parasail_nw_stats_table_striped_32',
    'parasail_nw_stats_table_striped_16',
    'parasail_nw_stats_table_striped_8',
    'parasail_nw_stats_table_striped_sat',
    'parasail_nw_stats_table_diag_64',
    'parasail_nw_stats_table_diag_32',
    'parasail_nw_stats_table_diag_16',
    'parasail_nw_stats_table_diag_8',
    'parasail_nw_stats_table_diag_sat',
    'parasail_nw_stats_rowcol_scan_64',
    'parasail_nw_stats_rowcol_scan_32',
    'parasail_nw_stats_rowcol_scan_16',
    'parasail_nw_stats_rowcol_scan_8',
    'parasail_nw_stats_rowcol_scan_sat',
    'parasail_nw_stats_rowcol_striped_64',
    'parasail_nw_stats_rowcol_striped_32',
    'parasail_nw_stats_rowcol_striped_16',
    'parasail_nw_stats_rowcol_striped_8',
    'parasail_nw_stats_rowcol_striped_sat',
    'parasail_nw_stats_rowcol_diag_64',
    'parasail_nw_stats_rowcol_diag_32',
    'parasail_nw_stats_rowcol_diag_16',
    'parasail_nw_stats_rowcol_diag_8',
    'parasail_nw_stats_rowcol_diag_sat',
    'parasail_sg_scan_64',
    'parasail_sg_scan_32',
    'parasail_sg_scan_16',
    'parasail_sg_scan_8',
    'parasail_sg_scan_sat',
    'parasail_sg_striped_64',
    'parasail_sg_striped_32',
    'parasail_sg_striped_16',
    'parasail_sg_striped_8',
    'parasail_sg_striped_sat',
    'parasail_sg_diag_64',
    'parasail_sg_diag_32',
    'parasail_sg_diag_16',
    'parasail_sg_diag_8',
    'parasail_sg_diag_sat',
    'parasail_sg_table_scan_64',
    'parasail_sg_table_scan_32',
    'parasail_sg_table_scan_16',
    'parasail_sg_table_scan_8',
    'parasail_sg_table_scan_sat',
    'parasail_sg_table_striped_64',
    'parasail_sg_table_striped_32',
    'parasail_sg_table_striped_16',
    'parasail_sg_table_striped_8',
    'parasail_sg_table_striped_sat',
    'parasail_sg_table_diag_64',
    'parasail_sg_table_diag_32',
    'parasail_sg_table_diag_16',
    'parasail_sg_table_diag_8',
    'parasail_sg_table_diag_sat',
    'parasail_sg_rowcol_scan_64',
    'parasail_sg_rowcol_scan_32',
    'parasail_sg_rowcol_scan_16',
    'parasail_sg_rowcol_scan_8',
    'parasail_sg_rowcol_scan_sat',
    'parasail_sg_rowcol_striped_64',
    'parasail_sg_rowcol_striped_32',
    'parasail_sg_rowcol_striped_16',
    'parasail_sg_rowcol_striped_8',
    'parasail_sg_rowcol_striped_sat',
    'parasail_sg_rowcol_diag_64',
    'parasail_sg_rowcol_diag_32',
    'parasail_sg_rowcol_diag_16',
    'parasail_sg_rowcol_diag_8',
    'parasail_sg_rowcol_diag_sat',
    'parasail_sg_trace_scan_64',
    'parasail_sg_trace_scan_32',
    'parasail_sg_trace_scan_16',
    'parasail_sg_trace_scan_8',
    'parasail_sg_trace_scan_sat',
    'parasail_sg_trace_striped_64',
    'parasail_sg_trace_striped_32',
    'parasail_sg_trace_striped_16',
    'parasail_sg_trace_striped_8',
    'parasail_sg_trace_striped_sat',
    'parasail_sg_trace_diag_64',
    'parasail_sg_trace_diag_32',
    'parasail_sg_trace_diag_16',
    'parasail_sg_trace_diag_8',
    'parasail_sg_trace_diag_sat',
    'parasail_sg_stats_scan_64',
    'parasail_sg_stats_scan_32',
    'parasail_sg_stats_scan_16',
    'parasail_sg_stats_scan_8',
    'parasail_sg_stats_scan_sat',
    'parasail_sg_stats_striped_64',
    'parasail_sg_stats_striped_32',
    'parasail_sg_stats_striped_16',
    'parasail_sg_stats_striped_8',
    'parasail_sg_stats_striped_sat',
    'parasail_sg_stats_diag_64',
    'parasail_sg_stats_diag_32',
    'parasail_sg_stats_diag_16',
    'parasail_sg_stats_diag_8',
    'parasail_sg_stats_diag_sat',
    'parasail_sg_stats_table_scan_64',
    'parasail_sg_stats_table_scan_32',
    'parasail_sg_stats_table_scan_16',
    'parasail_sg_stats_table_scan_8',
    'parasail_sg_stats_table_scan_sat',
    'parasail_sg_stats_table_striped_64',
    'parasail_sg_stats_table_striped_32',
    'parasail_sg_stats_table_striped_16',
    'parasail_sg_stats_table_striped_8',
    'parasail_sg_stats_table_striped_sat',
    'parasail_sg_stats_table_diag_64',
    'parasail_sg_stats_table_diag_32',
    'parasail_sg_stats_table_diag_16',
    'parasail_sg_stats_table_diag_8',
    'parasail_sg_stats_table_diag_sat',
    'parasail_sg_stats_rowcol_scan_64',
    'parasail_sg_stats_rowcol_scan_32',
    'parasail_sg_stats_rowcol_scan_16',
    'parasail_sg_stats_rowcol_scan_8',
    'parasail_sg_stats_rowcol_scan_sat',
    'parasail_sg_stats_rowcol_striped_64',
    'parasail_sg_stats_rowcol_striped_32',
    'parasail_sg_stats_rowcol_striped_16',
    'parasail_sg_stats_rowcol_striped_8',
    'parasail_sg_stats_rowcol_striped_sat',
    'parasail_sg_stats_rowcol_diag_64',
    'parasail_sg_stats_rowcol_diag_32',
    'parasail_sg_stats_rowcol_diag_16',
    'parasail_sg_stats_rowcol_diag_8',
    'parasail_sg_stats_rowcol_diag_sat',
    'parasail_sw_scan_64',
    'parasail_sw_scan_32',
    'parasail_sw_scan_16',
    'parasail_sw_scan_8',
    'parasail_sw_scan_sat',
    'parasail_sw_striped_64',
    'parasail_sw_striped_32',
    'parasail_sw_striped_16',
    'parasail_sw_striped_8',
    'parasail_sw_striped_sat',
    'parasail_sw_diag_64',
    'parasail_sw_diag_32',
    'parasail_sw_diag_16',
    'parasail_sw_diag_8',
    'parasail_sw_diag_sat',
    'parasail_sw_table_scan_64',
    'parasail_sw_table_scan_32',
    'parasail_sw_table_scan_16',
    'parasail_sw_table_scan_8',
    'parasail_sw_table_scan_sat',
    'parasail_sw_table_striped_64',
    'parasail_sw_table_striped_32',
    'parasail_sw_table_striped_16',
    'parasail_sw_table_striped_8',
    'parasail_sw_table_striped_sat',
    'parasail_sw_table_diag_64',
    'parasail_sw_table_diag_32',
    'parasail_sw_table_diag_16',
    'parasail_sw_table_diag_8',
    'parasail_sw_table_diag_sat',
    'parasail_sw_rowcol_scan_64',
    'parasail_sw_rowcol_scan_32',
    'parasail_sw_rowcol_scan_16',
    'parasail_sw_rowcol_scan_8',
    'parasail_sw_rowcol_scan_sat',
    'parasail_sw_rowcol_striped_64',
    'parasail_sw_rowcol_striped_32',
    'parasail_sw_rowcol_striped_16',
    'parasail_sw_rowcol_striped_8',
    'parasail_sw_rowcol_striped_sat',
    'parasail_sw_rowcol_diag_64',
    'parasail_sw_rowcol_diag_32',
    'parasail_sw_rowcol_diag_16',
    'parasail_sw_rowcol_diag_8',
    'parasail_sw_rowcol_diag_sat',
    'parasail_sw_trace_scan_64',
    'parasail_sw_trace_scan_32',
    'parasail_sw_trace_scan_16',
    'parasail_sw_trace_scan_8',
    'parasail_sw_trace_scan_sat',
    'parasail_sw_trace_striped_64',
    'parasail_sw_trace_striped_32',
    'parasail_sw_trace_striped_16',
    'parasail_sw_trace_striped_8',
    'parasail_sw_trace_striped_sat',
    'parasail_sw_trace_diag_64',
    'parasail_sw_trace_diag_32',
    'parasail_sw_trace_diag_16',
    'parasail_sw_trace_diag_8',
    'parasail_sw_trace_diag_sat',
    'parasail_sw_stats_scan_64',
    'parasail_sw_stats_scan_32',
    'parasail_sw_stats_scan_16',
    'parasail_sw_stats_scan_8',
    'parasail_sw_stats_scan_sat',
    'parasail_sw_stats_striped_64',
    'parasail_sw_stats_striped_32',
    'parasail_sw_stats_striped_16',
    'parasail_sw_stats_striped_8',
    'parasail_sw_stats_striped_sat',
    'parasail_sw_stats_diag_64',
    'parasail_sw_stats_diag_32',
    'parasail_sw_stats_diag_16',
    'parasail_sw_stats_diag_8',
    'parasail_sw_stats_diag_sat',
    'parasail_sw_stats_table_scan_64',
    'parasail_sw_stats_table_scan_32',
    'parasail_sw_stats_table_scan_16',
    'parasail_sw_stats_table_scan_8',
    'parasail_sw_stats_table_scan_sat',
    'parasail_sw_stats_table_striped_64',
    'parasail_sw_stats_table_striped_32',
    'parasail_sw_stats_table_striped_16',
    'parasail_sw_stats_table_striped_8',
    'parasail_sw_stats_table_striped_sat',
    'parasail_sw_stats_table_diag_64',
    'parasail_sw_stats_table_diag_32',
    'parasail_sw_stats_table_diag_16',
    'parasail_sw_stats_table_diag_8',
    'parasail_sw_stats_table_diag_sat',
    'parasail_sw_stats_rowcol_scan_64',
    'parasail_sw_stats_rowcol_scan_32',
    'parasail_sw_stats_rowcol_scan_16',
    'parasail_sw_stats_rowcol_scan_8',
    'parasail_sw_stats_rowcol_scan_sat',
    'parasail_sw_stats_rowcol_striped_64',
    'parasail_sw_stats_rowcol_striped_32',
    'parasail_sw_stats_rowcol_striped_16',
    'parasail_sw_stats_rowcol_striped_8',
    'parasail_sw_stats_rowcol_striped_sat',
    'parasail_sw_stats_rowcol_diag_64',
    'parasail_sw_stats_rowcol_diag_32',
    'parasail_sw_stats_rowcol_diag_16',
    'parasail_sw_stats_rowcol_diag_8',
    'parasail_sw_stats_rowcol_diag_sat',
]

SIGNATURE = """\
    parasail_result* _c_{name} "{name}"(
        const char * const s1, const int s1Len,
        const char * const s2, const int s2Len,
        const int open, const int gap,
        const parasail_matrix* matrix)
"""

CYTHON_IMPLEMENTATION = """\
def {name}(s1, s2, open_, extend, matrix):
    cdef parasail_result *result
    cdef Result wrapped_result

    result = _c_{name}(
        B(s1), len(s1), B(s2), len(s2), open_, extend,
        (<Matrix>matrix).pointer
    )
    if result != NULL:
        wrapped_result = Result(len(s1), len(s2))
        wrapped_result.pointer = result
        return wrapped_result

"""

HEADER = """
# autogenerated by tools/make_functions.py

from _parasail cimport parasail_result, parasail_matrix
from _parasail_base cimport Matrix
from _result cimport Result
from .util import B

cdef extern from "parasail.h":
"""


def write_parasail_defs(fname):
    with open(fname, "w") as fp:
        print(HEADER, file=fp)
        for name in FUNC_NAMES:
            print(SIGNATURE.format(name=name), file=fp)
        for name in FUNC_NAMES:
            print(CYTHON_IMPLEMENTATION.format(name=name), file=fp)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("output", help="where to write autogenerated stubs")
    ns = p.parse_args()

    write_parasail_defs(ns.output)


if __name__ == '__main__':
    main()
